name: Master Deploy

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: SSH into Azure VM
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.IP }}
        username: ayden
        password: ${{ secrets.VM_Pass }}
        script: |
          cd qr-image-drop
          sudo pkill gunicorn
          git pull
          ./prod.sh > nohup2.out 2> nohup2.err < /dev/null &
