name: Master Deploy

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
    - name: SSH into Azure VM
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.IP }}
        username: ayden
        password: ${{ secrets.VM_Pass }}
        script: |
          cd qr-image-drop
          echo ${{ secrets.VM_Pass }} | sudo -S pkill gunicorn
          git stash
          git pull
          git stash pop
          echo ${{ secrets.VM_Pass }} | sudo -S timeout 1000 ./prod.sh
